spring.application.name=loteria
# 1. Configuración de la conexión (Añadido DB_CLOSE_DELAY)
spring.datasource.url=jdbc:h2:mem:loteriadb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234

# 2. Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# 3. Acceso visual a la base de datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. Niveles de Log (Punto 5 del ejercicio)
# Para el día a día (INFO): No muestra datos privados (Requisito 3.b)
logging.level.com.helloword.loteria=INFO

# Para depuración (DEBUG): Muestra todo (Requisito 3.c)
# logging.level.com.helloword.loteria=DEBUG

# Opcional: Ver logs de las tablas creadas por tu compañero
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE