spring.application.name=loteria
# 1. Configuración de la conexión
spring.datasource.url=jdbc:h2:mem:loteriadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234

# 2. Configuración de JPA (Aquí está el truco)
# 'update' crea las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# 3. Acceso visual a la base de datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
